//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.PandaArmMsg
{
    [Serializable]
    public class ControlUnityArmGripperRequest : Message
    {
        public const string k_RosMessageName = "panda_arm_msg/ControlUnityArmGripper";
        public override string RosMessageName => k_RosMessageName;

        //  设置gripper的开度
        public double gripper_position;

        public ControlUnityArmGripperRequest()
        {
            this.gripper_position = 0.0;
        }

        public ControlUnityArmGripperRequest(double gripper_position)
        {
            this.gripper_position = gripper_position;
        }

        public static ControlUnityArmGripperRequest Deserialize(MessageDeserializer deserializer) => new ControlUnityArmGripperRequest(deserializer);

        private ControlUnityArmGripperRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.gripper_position);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.gripper_position);
        }

        public override string ToString()
        {
            return "ControlUnityArmGripperRequest: " +
            "\ngripper_position: " + gripper_position.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
