//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.PandaArmMsg
{
    [Serializable]
    public class ControlRvizArmResponse : Message
    {
        public const string k_RosMessageName = "panda_arm_msg/ControlRvizArm";
        public override string RosMessageName => k_RosMessageName;

        //  是否发出成功
        public bool success;

        public ControlRvizArmResponse()
        {
            this.success = false;
        }

        public ControlRvizArmResponse(bool success)
        {
            this.success = success;
        }

        public static ControlRvizArmResponse Deserialize(MessageDeserializer deserializer) => new ControlRvizArmResponse(deserializer);

        private ControlRvizArmResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.success);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.success);
        }

        public override string ToString()
        {
            return "ControlRvizArmResponse: " +
            "\nsuccess: " + success.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
