//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.PandaArmMsg
{
    [Serializable]
    public class ControlRvizArmRequest : Message
    {
        public const string k_RosMessageName = "panda_arm_msg/ControlRvizArm";
        public override string RosMessageName => k_RosMessageName;

        //  位置
        public double[] position;
        //  开合
        public string open_or_close;

        public ControlRvizArmRequest()
        {
            this.position = new double[0];
            this.open_or_close = "";
        }

        public ControlRvizArmRequest(double[] position, string open_or_close)
        {
            this.position = position;
            this.open_or_close = open_or_close;
        }

        public static ControlRvizArmRequest Deserialize(MessageDeserializer deserializer) => new ControlRvizArmRequest(deserializer);

        private ControlRvizArmRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.position, sizeof(double), deserializer.ReadLength());
            deserializer.Read(out this.open_or_close);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.position);
            serializer.Write(this.position);
            serializer.Write(this.open_or_close);
        }

        public override string ToString()
        {
            return "ControlRvizArmRequest: " +
            "\nposition: " + System.String.Join(", ", position.ToList()) +
            "\nopen_or_close: " + open_or_close.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
