//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.PandaArmMsg
{
    [Serializable]
    public class ControlUnityArmRequest : Message
    {
        public const string k_RosMessageName = "panda_arm_msg/ControlUnityArm";
        public override string RosMessageName => k_RosMessageName;

        //  机械臂轨迹
        public Trajectory.JointTrajectoryMsg joint_trajectory;

        public ControlUnityArmRequest()
        {
            this.joint_trajectory = new Trajectory.JointTrajectoryMsg();
        }

        public ControlUnityArmRequest(Trajectory.JointTrajectoryMsg joint_trajectory)
        {
            this.joint_trajectory = joint_trajectory;
        }

        public static ControlUnityArmRequest Deserialize(MessageDeserializer deserializer) => new ControlUnityArmRequest(deserializer);

        private ControlUnityArmRequest(MessageDeserializer deserializer)
        {
            this.joint_trajectory = Trajectory.JointTrajectoryMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.joint_trajectory);
        }

        public override string ToString()
        {
            return "ControlUnityArmRequest: " +
            "\njoint_trajectory: " + joint_trajectory.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
