//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.PandaArmMsg
{
    [Serializable]
    public class YoloImageRequest : Message
    {
        public const string k_RosMessageName = "panda_arm_msg/YoloImage";
        public override string RosMessageName => k_RosMessageName;

        //  想要获取的帧数
        public ushort num_image;

        public YoloImageRequest()
        {
            this.num_image = 0;
        }

        public YoloImageRequest(ushort num_image)
        {
            this.num_image = num_image;
        }

        public static YoloImageRequest Deserialize(MessageDeserializer deserializer) => new YoloImageRequest(deserializer);

        private YoloImageRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.num_image);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.num_image);
        }

        public override string ToString()
        {
            return "YoloImageRequest: " +
            "\nnum_image: " + num_image.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
