//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.PandaArmMsg
{
    [Serializable]
    public class YoloImageResponse : Message
    {
        public const string k_RosMessageName = "panda_arm_msg/YoloImage";
        public override string RosMessageName => k_RosMessageName;

        //  是否发出成功
        public bool success;
        public Sensor.ImageMsg[] images;

        public YoloImageResponse()
        {
            this.success = false;
            this.images = new Sensor.ImageMsg[0];
        }

        public YoloImageResponse(bool success, Sensor.ImageMsg[] images)
        {
            this.success = success;
            this.images = images;
        }

        public static YoloImageResponse Deserialize(MessageDeserializer deserializer) => new YoloImageResponse(deserializer);

        private YoloImageResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.success);
            deserializer.Read(out this.images, Sensor.ImageMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.success);
            serializer.WriteLength(this.images);
            serializer.Write(this.images);
        }

        public override string ToString()
        {
            return "YoloImageResponse: " +
            "\nsuccess: " + success.ToString() +
            "\nimages: " + System.String.Join(", ", images.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
